language: node_js
version: 1.0
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run test
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
jobs:
  include:
    - stage: Tagging
      if: (branch = master) AND (tag IS blank)
      after_success: source ./deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: mJQHF3GdCzCFo+2sB6PEtJJjbbleE92fCugN9uIeOynsXYpZ169/2QGhWp0hGpjm3/BNfR07lnHlowCTAorQmsMVdyW6Ud8Ob9g8N45kv35QyibiaO75BBReMuKQbSXx3tfNWrlDcNmpGv/ja0qb4vJEJBL96KjOOEHNA7fdJE88MR35muLZx1GxTkKiAGljhzGHfz/4wFJy3TpVMIB3dQ8vwoWF1Gt8WFAUg8ZxbyWcz4laIKAjZ2F8pdF+dTiRJWEaCiCu8MluCdGHre4LJ4YEAV6P62G8ohN5YKneh+X6OXtGvK497+TA1Hae7xBjzNn3j1ExekUw4aglSj5jTIZ3TA7C5OmBNk23I1aBiHVv2NB+eJNsZVWP0OXxghMkSwPnOIePJr14Que9uA7sYvs5rQ6yuYh7dVMZdxAZAU906HC2J1L/ZXJwDljIg4VXk888dtS/q9ApeR7NJnXXDXkSKmbJEB7D9ftcWlZlnOvqyDKuuKksvCl1k947aBDgvV8A+LNoe1G/wWMTN3/87W4400biLYqPW9hn2G9GVmpyTGqr1atKv+CrPK3NzubBPF96b5CTsG5YOegv1W0eNQ85eVbsHuJvyZQqypN8cohrTEFSSDHpcQ2pYelcWfrA+j8AExB4mUsd/6Bj7oMEBXBVCYdHz5HxqqEiEnDNTQg=
        name: Build $PACKAGE_VERSION
        on:
          repo: guillotinaweb/grange-core
          branch: master
          tags: true
    - stage: NPM release
      if: tag IS present
      before_deploy: cd dist/grange-core
      deploy:
        provider: npm
        edge: true
        email: ebrehault@gmail.com
        skip_cleanup: true
        api_key:
          secure: j2PA/ZVT7SxyGem/e81N86JX50Ij7RL88DN5RnUqLWohW3c2kFU9IgL4AVccX12AoXSinwe5sqHAs85hZzM7sgTwFirsuUKpfDbRUzx3RixDBMU482RX3v9IddYqrP4Y3Lz8og9NaTPlrwnPwh4yoy4H2swbswk2XqpoRr551QNRK1b3xPAogf6Ie9phRJuLxaRKCyYOy5EcCbOobn2/iH26lM409Zb6EDsCGSxz/i7djGDBWqWdFsKDTJRYmycCvJdwciOV6beQVOOtDvO2X9PBtLH2PIkLqkOoIDwL0PLGEFxZxIcY1/54zIBNHfQX3xGiRwF2wD4ihp46ZQpGOW669HLsPWikSS5XJ+VZ59AOS7aKhOsyFudQauFxIf7uf9UVwOQRlx2qXQJ1DcBD2Ttus6op3hYnbFGnFTvo7LGtzlO5L3Hwth3V5XiEe8EN1OBpItrLrUg03XNj5OCYEPn5iQm0g2j0cN93G5tRPTtzGECLtFoyS9vH+EGYgeo3WOLkwI/v3T2B11h3ZDe4cCLUw3ONft/XHKl8QjKyNrzb8Mx+Efe4sSm/zA6byH0XniF5hhVBSXwN7eivW9qRuEtZXrV8r1TbyUZ5pQ4CUqLNh21R4XNBFQReJ/KaPIH6MU49NwLKXObFwS/rLN37QnOLovBQyIy8FBEgxfWN/0U=
        on:
          tags: true
          repo: guillotinaweb/grange-core
          branch: master
